name: Bump version

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    environment: release
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.pat }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.pat }}
